football.api.url=https://api.football-data.org/v4
football.api.token=8bee7933933947aa8e115d4a621f0bc8

spring.application.name=FootballScope
spring.datasource.url=jdbc:postgresql://localhost:5432/footballscope
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true